# Portrait Preview Webapp - Frame Asset Definitions
# Maps product sizes and styles to frame PNG files and opening coordinates

frames:
  # 5x7 frame assets
  - product_slug: "5x7_basic"
    style: "cherry"
    asset_path: "assets/frames/single/frame_5x7_cherry.png"
    opening_boxes: [[0.15, 0.1, 0.85, 0.9]]  # [x1, y1, x2, y2] relative coordinates 0-1
  
  - product_slug: "5x7_basic"
    style: "black"
    asset_path: "assets/frames/single/frame_5x7_black.png"
    opening_boxes: [[0.15, 0.1, 0.85, 0.9]]
  
  - product_slug: "5x7_basic"
    style: "white"
    asset_path: "assets/frames/single/frame_5x7_white.png"
    opening_boxes: [[0.15, 0.1, 0.85, 0.9]]

  # 8x10 frame assets
  - product_slug: "8x10_basic"
    style: "cherry"
    asset_path: "assets/frames/single/frame_8x10_cherry.png"
    opening_boxes: [[0.12, 0.08, 0.88, 0.92]]
  
  - product_slug: "8x10_basic"
    style: "black"
    asset_path: "assets/frames/single/frame_8x10_black.png"
    opening_boxes: [[0.12, 0.08, 0.88, 0.92]]
  
  - product_slug: "8x10_basic"
    style: "white"
    asset_path: "assets/frames/single/frame_8x10_white.png"
    opening_boxes: [[0.12, 0.08, 0.88, 0.92]]
  
  - product_slug: "8x10_basic"
    style: "digital_mat_black_cherry"
    asset_path: "assets/frames/single/frame_8x10_digital_mat_black_cherry.png"
    opening_boxes: [[0.20, 0.15, 0.80, 0.85]]  # Smaller opening due to mat

  # 10x13 frame assets
  - product_slug: "10x13_basic"
    style: "cherry"
    asset_path: "assets/frames/single/frame_10x13_cherry.png"
    opening_boxes: [[0.10, 0.08, 0.90, 0.92]]
  
  - product_slug: "10x13_basic"
    style: "black"
    asset_path: "assets/frames/single/frame_10x13_black.png"
    opening_boxes: [[0.10, 0.08, 0.90, 0.92]]

  # 16x20 frame assets
  - product_slug: "16x20_basic"
    style: "cherry"
    asset_path: "assets/frames/single/frame_16x20_cherry.png"
    opening_boxes: [[0.08, 0.06, 0.92, 0.94]]
  
  - product_slug: "16x20_basic"
    style: "black"
    asset_path: "assets/frames/single/frame_16x20_black.png"
    opening_boxes: [[0.08, 0.06, 0.92, 0.94]]

  # 20x24 frame assets  
  - product_slug: "20x24_basic"
    style: "cherry"
    asset_path: "assets/frames/single/frame_20x24_cherry.png"
    opening_boxes: [[0.06, 0.05, 0.94, 0.95]]
  
  - product_slug: "20x24_basic"
    style: "black"
    asset_path: "assets/frames/single/frame_20x24_black.png"
    opening_boxes: [[0.06, 0.05, 0.94, 0.95]]

  # Multi-opening frame templates
  - product_slug: "10x20_trio_black_cherry"
    style: "black_cherry"
    asset_path: "assets/frames/multi/trio_10x20_black_cherry.png"
    opening_boxes: 
      - [0.05, 0.1, 0.30, 0.9]   # Left opening
      - [0.35, 0.1, 0.65, 0.9]   # Center opening  
      - [0.70, 0.1, 0.95, 0.9]   # Right opening

  - product_slug: "5x10_triple_black_cherry"
    style: "black_cherry"
    asset_path: "assets/frames/multi/triple_5x10_black_cherry.png"
    opening_boxes:
      - [0.1, 0.05, 0.9, 0.30]   # Top opening
      - [0.1, 0.35, 0.9, 0.65]   # Middle opening
      - [0.1, 0.70, 0.9, 0.95]   # Bottom opening

# Multi-opening template definitions
multi_opening_templates:
  trio_10x20:
    name: "10x20 Trio Portrait Frame"
    description: "Three portrait openings in landscape frame"
    opening_count: 3
    base_aspect_ratio: 0.5  # 10/20 = 0.5 (landscape)
    
  triple_5x10:
    name: "5x10 Triple Opening Frame"  
    description: "Three landscape openings stacked vertically"
    opening_count: 3
    base_aspect_ratio: 0.5  # 5/10 = 0.5 (portrait frame)

# Wallet sheet template
wallet_template:
  name: "Wallet Sheet 8-up"
  asset_path: "assets/frames/multi/wallet_sheet_template.png"
  grid_layout:
    rows: 4
    cols: 2
    cell_openings:
      - [0.05, 0.05, 0.45, 0.22]   # Top left
      - [0.55, 0.05, 0.95, 0.22]   # Top right
      - [0.05, 0.27, 0.45, 0.47]   # Second row left
      - [0.55, 0.27, 0.95, 0.47]   # Second row right
      - [0.05, 0.52, 0.45, 0.72]   # Third row left
      - [0.55, 0.52, 0.95, 0.72]   # Third row right
      - [0.05, 0.77, 0.45, 0.97]   # Bottom left
      - [0.55, 0.77, 0.95, 0.97]   # Bottom right 