# Product Configuration for Portrait Preview Webapp
# Based on POINTS SHEET & CODES.csv

products:
  # WALLETS
  - slug: "wallets_200"
    name: "Sheet of 8 Wallets"
    code: "200"
    width_in: 2.5
    height_in: 3.5
    count_images: 8
    frame_style_default: "none"
    parsing_patterns: ["200", "sheet of 8 wallets", "wallets"]

  # WALLET SHEETS (for 2x4 layout)
  - slug: "wallet_sheet"
    name: "Wallet Sheet (2x4 Grid - 8 wallets)"
    code: "200_sheet"
    width_in: 10.0  # 8x10 landscape sheet width
    height_in: 8.0   # 8x10 landscape sheet height
    count_images: 8
    frame_style_default: "none"
    parsing_patterns: ["200_sheet", "wallet sheet", "wallet 2x4"]

  # 5x7 LANDSCAPE SHEETS (for side-by-side layout)
  - slug: "5x7_sheet_landscape"
    name: "5x7 Landscape Sheet (2 Side-by-Side)"
    code: "570_sheet"
    width_in: 10.0  # 10" wide for two 5" images side by side
    height_in: 7.0   # 7" tall to match 5x7 image height
    count_images: 2
    frame_style_default: "none"
    parsing_patterns: ["570_sheet", "5x7 sheet", "pair 5x7"]

  # 3.5x5 PORTRAIT SHEETS (for 2x2 layout)
  - slug: "3x5_sheet_portrait"
    name: "3.5x5 Portrait Sheet (2x2 Grid - 4 images)"
    code: "350_sheet"
    width_in: 7.0   # 7" wide portrait sheet
    height_in: 10.0  # 10" tall portrait sheet  
    count_images: 4
    frame_style_default: "none"
    parsing_patterns: ["350_sheet", "3.5x5 sheet", "3x5 2x2 grid"]

  # 3.5x5 BASIC
  - slug: "3x5_basic_350"
    name: "3.5x5 Basic (1 sheet of 4)"
    code: "350"
    width_in: 3.5
    height_in: 5.0
    count_images: 4
    frame_style_default: "none"
    parsing_patterns: ["350", "3.5x5", "3x5", "basic 1 sheet of 4"]

  # 5x7 BASIC/PRESTIGE/KEEPSAKE
  - slug: "5x7_basic_570"
    name: "Pair 5x7 Basic"
    code: "570"
    width_in: 5.0
    height_in: 7.0
    count_images: 2
    frame_style_default: "none"
    parsing_patterns: ["570", "pair 5x7 basic", "5x7 basic"]

  - slug: "5x7_prestige_571"
    name: "Pair 5x7 Prestige"
    code: "571"
    width_in: 5.0
    height_in: 7.0
    count_images: 2
    frame_style_default: "none"
    parsing_patterns: ["571", "pair 5x7 prestige", "5x7 prestige"]

  - slug: "5x7_keepsake_572"
    name: "Pair 5x7 Keepsake"
    code: "572"
    width_in: 5.0
    height_in: 7.0
    count_images: 2
    frame_style_default: "none"
    parsing_patterns: ["572", "pair 5x7 keepsake", "5x7 keepsake"]

  # 8x10 BASIC/PRESTIGE/KEEPSAKE
  - slug: "8x10_basic_001"
    name: "Complimentary 8x10 Basic"
    code: "001"
    width_in: 8.0
    height_in: 10.0
    count_images: 1
    frame_style_default: "none"
    parsing_patterns: ["001", "complimentary 8x10 basic", "8x10 basic"]

  - slug: "8x10_basic_810"
    name: "8x10 Basic"
    code: "810"
    width_in: 8.0
    height_in: 10.0
    count_images: 1
    frame_style_default: "none"
    parsing_patterns: ["810", "8x10 basic"]

  - slug: "8x10_prestige_002"
    name: "Complimentary 8x10 Prestige"
    code: "002"
    width_in: 8.0
    height_in: 10.0
    count_images: 1
    frame_style_default: "none"
    parsing_patterns: ["002", "complimentary 8x10 upgraded to prestige", "8x10 prestige"]

  - slug: "8x10_prestige_811"
    name: "8x10 Prestige"
    code: "811"
    width_in: 8.0
    height_in: 10.0
    count_images: 1
    frame_style_default: "none"
    parsing_patterns: ["811", "8x10 prestige"]

  - slug: "8x10_keepsake_003"
    name: "Complimentary 8x10 Keepsake"
    code: "003"
    width_in: 8.0
    height_in: 10.0
    count_images: 1
    frame_style_default: "none"
    parsing_patterns: ["003", "complimentary 8x10 upgraded to keepsake", "8x10 keepsake"]

  - slug: "8x10_keepsake_812"
    name: "8x10 Keepsake"
    code: "812"
    width_in: 8.0
    height_in: 10.0
    count_images: 1
    frame_style_default: "none"
    parsing_patterns: ["812", "8x10 keepsake"]

  # 10x13 BASIC/PRESTIGE/KEEPSAKE
  - slug: "10x13_basic_1013"
    name: "10x13 Basic"
    code: "1013"
    width_in: 10.0
    height_in: 13.0
    count_images: 1
    frame_style_default: "none"
    parsing_patterns: ["1013", "10x13 basic"]

  - slug: "10x13_prestige_1014"
    name: "10x13 Prestige"
    code: "1014"
    width_in: 10.0
    height_in: 13.0
    count_images: 1
    frame_style_default: "none"
    parsing_patterns: ["1014", "10x13 prestige"]

  - slug: "10x13_keepsake_1015"
    name: "10x13 Keepsake"
    code: "1015"
    width_in: 10.0
    height_in: 13.0
    count_images: 1
    frame_style_default: "none"
    parsing_patterns: ["1015", "10x13 keepsake"]

  # 16x20 BASIC/PRESTIGE/KEEPSAKE
  - slug: "16x20_basic_1620"
    name: "16x20 Basic"
    code: "1620"
    width_in: 16.0
    height_in: 20.0
    count_images: 1
    frame_style_default: "none"
    parsing_patterns: ["1620", "16x20 basic"]

  - slug: "16x20_prestige_1621"
    name: "16x20 Prestige"
    code: "1621"
    width_in: 16.0
    height_in: 20.0
    count_images: 1
    frame_style_default: "none"
    parsing_patterns: ["1621", "16x20 prestige"]

  - slug: "16x20_keepsake_1622"
    name: "16x20 Keepsake"
    code: "1622"
    width_in: 16.0
    height_in: 20.0
    count_images: 1
    frame_style_default: "none"
    parsing_patterns: ["1622", "16x20 keepsake"]

  # 20x24 BASIC/PRESTIGE/KEEPSAKE
  - slug: "20x24_basic_2024"
    name: "20x24 Basic"
    code: "2024"
    width_in: 20.0
    height_in: 24.0
    count_images: 1
    frame_style_default: "none"
    parsing_patterns: ["2024", "20x24 basic"]

  - slug: "20x24_prestige_2025"
    name: "20x24 Prestige"
    code: "2025"
    width_in: 20.0
    height_in: 24.0
    count_images: 1
    frame_style_default: "none"
    parsing_patterns: ["2025", "20x24 prestige"]

  - slug: "20x24_keepsake_2026"
    name: "20x24 Keepsake"
    code: "2026"
    width_in: 20.0
    height_in: 24.0
    count_images: 1
    frame_style_default: "none"
    parsing_patterns: ["2026", "20x24 keepsake"]

  # 5x10 TRIO PORTRAITS
  - slug: "5x10_trio_510"
    name: "5x10 Trio Portrait (Creme Mat, Cherry Frame)"
    code: "510"
    width_in: 5.0
    height_in: 10.0
    count_images: 3
    frame_style_default: "cherry"
    multi_opening_template: "trio_horizontal"
    parsing_patterns: ["510", "5x10 trio portrait", "creme mat and cherry frame"]

  - slug: "5x10_trio_510_1"
    name: "5x10 Trio Portrait (White Mat, Cherry Frame)"
    code: "510.1"
    width_in: 5.0
    height_in: 10.0
    count_images: 3
    frame_style_default: "cherry"
    multi_opening_template: "trio_horizontal"
    parsing_patterns: ["510.1", "5x10 trio portrait", "white mat and cherry frame"]

  - slug: "5x10_trio_510_2"
    name: "5x10 Trio Portrait (Gray Mat, Cherry Frame)"
    code: "510.2"
    width_in: 5.0
    height_in: 10.0
    count_images: 3
    frame_style_default: "cherry"
    multi_opening_template: "trio_horizontal"
    parsing_patterns: ["510.2", "5x10 trio portrait", "gray mat and cherry frame"]

  - slug: "5x10_trio_510_3"
    name: "5x10 Trio Portrait (Black Mat, Cherry Frame)"
    code: "510.3"
    width_in: 5.0
    height_in: 10.0
    count_images: 3
    frame_style_default: "cherry"
    multi_opening_template: "trio_horizontal"
    parsing_patterns: ["510.3", "5x10 trio portrait", "black mat and cherry frame", "triple opening with black digital mat and cherry frame"]

  - slug: "5x10_trio_511"
    name: "5x10 Trio Portrait (Creme Mat, Black Frame)"
    code: "511"
    width_in: 5.0
    height_in: 10.0
    count_images: 3
    frame_style_default: "black"
    multi_opening_template: "trio_horizontal"
    parsing_patterns: ["511", "5x10 trio portrait", "creme mat and black frame"]

  - slug: "5x10_trio_511_1"
    name: "5x10 Trio Portrait (White Mat, Black Frame)"
    code: "511.1"
    width_in: 5.0
    height_in: 10.0
    count_images: 3
    frame_style_default: "black"
    multi_opening_template: "trio_horizontal"
    parsing_patterns: ["511.1", "5x10 trio portrait", "white mat and black frame"]

  - slug: "5x10_trio_511_2"
    name: "5x10 Trio Portrait (Gray Mat, Black Frame)"
    code: "511.2"
    width_in: 5.0
    height_in: 10.0
    count_images: 3
    frame_style_default: "black"
    multi_opening_template: "trio_horizontal"
    parsing_patterns: ["511.2", "5x10 trio portrait", "gray mat and black frame"]

  - slug: "5x10_trio_511_3"
    name: "5x10 Trio Portrait (Black Mat, Black Frame)"
    code: "511.3"
    width_in: 5.0
    height_in: 10.0
    count_images: 3
    frame_style_default: "black"
    multi_opening_template: "trio_horizontal"
    parsing_patterns: ["511.3", "5x10 trio portrait", "black mat and black frame"]

  # 10x20 TRIO PORTRAITS
  - slug: "10x20_trio_1020"
    name: "10x20 Trio Portrait (White Mat, Black Frame)"
    code: "1020"
    width_in: 10.0
    height_in: 20.0
    count_images: 3
    frame_style_default: "black"
    multi_opening_template: "trio_horizontal"
    parsing_patterns: ["1020", "10x20 trio portrait", "white digital mat, black frame"]

  - slug: "10x20_trio_1020_1"
    name: "10x20 Trio Portrait (White Mat, Cherry Frame)"
    code: "1020.1"
    width_in: 10.0
    height_in: 20.0
    count_images: 3
    frame_style_default: "cherry"
    multi_opening_template: "trio_horizontal"
    parsing_patterns: ["1020.1", "10x20 trio portrait", "white digital mat, cherry frame"]

  - slug: "10x20_trio_1020_2"
    name: "10x20 Trio Portrait (Gray Mat, Black Frame)"
    code: "1020.2"
    width_in: 10.0
    height_in: 20.0
    count_images: 3
    frame_style_default: "black"
    multi_opening_template: "trio_horizontal"
    parsing_patterns: ["1020.2", "10x20 trio portrait", "gray digital mat, black frame"]

  - slug: "10x20_trio_1020_3"
    name: "10x20 Trio Portrait (Gray Mat, Cherry Frame)"
    code: "1020.3"
    width_in: 10.0
    height_in: 20.0
    count_images: 3
    frame_style_default: "cherry"
    multi_opening_template: "trio_horizontal"
    parsing_patterns: ["1020.3", "10x20 trio portrait", "gray digital mat, cherry frame"]

  - slug: "10x20_trio_1020_4"
    name: "10x20 Trio Portrait (Black Mat, Black Frame)"
    code: "1020.4"
    width_in: 10.0
    height_in: 20.0
    count_images: 3
    frame_style_default: "black"
    multi_opening_template: "trio_horizontal"
    parsing_patterns: ["1020.4", "10x20 trio portrait", "black digital mat, black frame"]

  - slug: "10x20_trio_1020_5"
    name: "10x20 Trio Portrait (Black Mat, Cherry Frame)"
    code: "1020.5"
    width_in: 10.0
    height_in: 20.0
    count_images: 3
    frame_style_default: "cherry"
    multi_opening_template: "trio_horizontal"
    parsing_patterns: ["1020.5", "10x20 trio portrait", "black digital mat, cherry frame"]

  - slug: "10x20_trio_1020_6"
    name: "10x20 Trio Portrait (Creme Mat, Black Frame)"
    code: "1020.6"
    width_in: 10.0
    height_in: 20.0
    count_images: 3
    frame_style_default: "black"
    multi_opening_template: "trio_horizontal"
    parsing_patterns: ["1020.6", "10x20 trio portrait", "creme digital mat, black frame"]

  - slug: "10x20_trio_1020_7"
    name: "10x20 Trio Portrait (Creme Mat, Cherry Frame)"
    code: "1020.7"
    width_in: 10.0
    height_in: 20.0
    count_images: 3
    frame_style_default: "cherry"
    multi_opening_template: "trio_horizontal"
    parsing_patterns: ["1020.7", "10x20 trio portrait", "creme digital mat, cherry frame"]

  # STAFF COMPLIMENTARY
  - slug: "staff_8x10_basic_9111"
    name: "Staff Complimentary 8x10 Basic"
    code: "9111"
    width_in: 8.0
    height_in: 10.0
    count_images: 1
    frame_style_default: "none"
    parsing_patterns: ["9111", "staff complimentary 8x10 basic"]

  - slug: "staff_8x10_prestige_9112"
    name: "Staff Complimentary 8x10 Prestige"
    code: "9112"
    width_in: 8.0
    height_in: 10.0
    count_images: 1
    frame_style_default: "none"
    parsing_patterns: ["9112", "staff complimentary 8x10 upgraded to prestige"]

  - slug: "staff_8x10_keepsake_9113"
    name: "Staff Complimentary 8x10 Keepsake"
    code: "9113"
    width_in: 8.0
    height_in: 10.0
    count_images: 1
    frame_style_default: "none"
    parsing_patterns: ["9113", "staff complimentary 8x10 upgraded to keepsake"] 