# Portrait Preview Webapp - Main Settings Configuration
# Global application settings with sensible defaults

# Flask configuration
SECRET_KEY: "dev-key-change-in-production"
FLASK_ENV: "development"
DEBUG: true

# File paths and storage
UPLOAD_FOLDER: "app/static/previews"
TEMP_FOLDER: "tmp"
LOG_FILE: "logs/app.log"
LOG_LEVEL: "INFO"
ASSETS_DIRECTORY: "assets"  # Root directory for frame/background assets
DEFAULT_BACKGROUND: "Virtual Background 2021.jpg"

# OCR settings
OCR_PSM: 6  # Assume a single uniform block of text
OCR_OEM: 3  # Default OCR Engine Mode
OCR_MIN_CONFIDENCE: 50.0

# Image processing settings
MAX_UPLOAD_SIZE: 20971520  # 20MB in bytes
ALLOWED_EXTENSIONS: [".jpg", ".jpeg", ".png", ".tif", ".tiff"]
OUTPUT_DPI: 300           # Output resolution for final images
AUTO_ENHANCE: true        # Apply automatic image enhancements
CROP_METHOD: "center"     # Options: center, top, left

# Image processing - final adjustments
FINAL_ADJUSTMENTS:
  sharpening: 0.1         # 0.0 to 1.0, amount of sharpening to apply
  sharpen_radius: 1.0     # Sharpening radius
  sharpen_threshold: 3    # Sharpening threshold
  contrast: 1.05          # Contrast adjustment (1.0 = no change)
  brightness: 1.0         # Brightness adjustment (1.0 = no change)
  saturation: 1.02        # Saturation adjustment (1.0 = no change)

# Layout engine settings
LAYOUT:
  background_strategy: "center_crop"  # center_crop, center_fit, stretch, tile
  frame_strategy: "center_fit"        # center_fit, exact_size, center_crop
  margin_px: 16                       # Minimum margin between items and edges
  min_item_size_px: 60               # Minimum size for any print item
  max_item_size_ratio: 0.8           # Maximum item size as ratio of background width

# Branding settings
BRANDING:
  watermark_enabled: true
  watermark_text: "PREVIEW"
  logo_enabled: false
  logo_filename: "logo.png"
  logo_position: "bottom_right"  # bottom_right, bottom_left, top_right, top_left

# UI and display settings  
BACKGROUND_DEFAULT: "Virtual Background 2021.jpg"
SHOW_LABELS: false         # Show size labels under items
QUANTITY_BADGE_ENABLED: true  # Show quantity badges (×2, ×8, etc.)

# Legacy settings (for backwards compatibility)
PX_PER_INCH_DEFAULT: 40.0  # Display pixels per print inch
MAX_PREVIEW_WIDTH: 1920    # Maximum background width
CROPPING_POLICY: "center_crop"  # or "letterbox"

# Development and debugging
KEEP_WORK_DIRS: false      # Keep temp directories for debugging
DEBUG_OCR_OVERLAYS: false  # Generate OCR debug images 